"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.DiscordColor = void 0;
var DiscordColor;
(function (DiscordColor) {
    DiscordColor[DiscordColor["Eagle"] = 2172744] = "Eagle";
    DiscordColor[DiscordColor["Default"] = 0] = "Default";
    DiscordColor[DiscordColor["Aqua"] = 1752220] = "Aqua";
    DiscordColor[DiscordColor["DarkAqua"] = 1146986] = "DarkAqua";
    DiscordColor[DiscordColor["Green"] = 5763719] = "Green";
    DiscordColor[DiscordColor["DarkGreen"] = 2067276] = "DarkGreen";
    DiscordColor[DiscordColor["Blue"] = 3447003] = "Blue";
    DiscordColor[DiscordColor["DarkBlue"] = 2123412] = "DarkBlue";
    DiscordColor[DiscordColor["Purple"] = 10181046] = "Purple";
    DiscordColor[DiscordColor["DarkPurple"] = 7419530] = "DarkPurple";
    DiscordColor[DiscordColor["LuminousVividPink"] = 15277667] = "LuminousVividPink";
    DiscordColor[DiscordColor["DarkVividPink"] = 11342935] = "DarkVividPink";
    DiscordColor[DiscordColor["Gold"] = 15844367] = "Gold";
    DiscordColor[DiscordColor["DarkGold"] = 12745742] = "DarkGold";
    DiscordColor[DiscordColor["Orange"] = 15105570] = "Orange";
    DiscordColor[DiscordColor["DarkOrange"] = 11027200] = "DarkOrange";
    DiscordColor[DiscordColor["Red"] = 15548997] = "Red";
    DiscordColor[DiscordColor["DarkRed"] = 10038562] = "DarkRed";
    DiscordColor[DiscordColor["Grey"] = 9807270] = "Grey";
    DiscordColor[DiscordColor["DarkGrey"] = 9936031] = "DarkGrey";
    DiscordColor[DiscordColor["DarkerGrey"] = 8359053] = "DarkerGrey";
    DiscordColor[DiscordColor["LightGrey"] = 12370112] = "LightGrey";
    DiscordColor[DiscordColor["Navy"] = 3426654] = "Navy";
    DiscordColor[DiscordColor["DarkNavy"] = 2899536] = "DarkNavy";
    DiscordColor[DiscordColor["Yellow"] = 16776960] = "Yellow";
    DiscordColor[DiscordColor["White"] = 16777215] = "White";
    DiscordColor[DiscordColor["Greyple"] = 10070709] = "Greyple";
    DiscordColor[DiscordColor["Black"] = 2303786] = "Black";
    DiscordColor[DiscordColor["DarkButNotBlack"] = 2895667] = "DarkButNotBlack";
    DiscordColor[DiscordColor["NotQuiteBlack"] = 2303786] = "NotQuiteBlack";
    DiscordColor[DiscordColor["Blurple"] = 5793266] = "Blurple";
    DiscordColor[DiscordColor["Fuchsia"] = 15418782] = "Fuchsia";
})(DiscordColor = exports.DiscordColor || (exports.DiscordColor = {}));
